@startuml
' skinparam handwritten true
skinparam monochrome true
hide circle
skinparam packageStyle rectangle

package "CS Wiktionary" as Wiktionary {
  class XMLDump {
    - title
    - page
  }
  class ScrapedData {
    - word
    - part of speech
    - ethymology
    - hyphenation
    - meaning
  }
  XMLDump -right- ScrapedData: title ... word
}



package "CS Hunspell Dictionary" as Hunspell {
  class dic {
    - word
    - tags
  }
  class aff {
    - tag
    - prefix/suffix
    - content
    - condition
  }
  dic -- aff
}

package FrequencyWords {
  class "cs" as FrequencyWordsCs {
    - word
    - frequency
  }
}

package StopWords {
  class "cs" as StopWordsCs {
    - word
  }
}

ScrapedData -- dic
StopWordsCs -- dic
FrequencyWordsCs -- dic

@enduml
