# Find all non-stopwords, order by frequency.
# Select word, PoS and freq.
PREFIX ex:  <http://example.com/#>
PREFIX lemon: <http://lemon-model.net/lemon#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX lexinfo: <http://www.lexinfo.net/ontology/2.0/lexinfo#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?word ?freq ?pos
WHERE {
	?wordUri lemon:lexicalForm ?word ;
          owl:sameAs/ex:wordFrequency ?freq;
                    owl:sameAs/ex:stopword ?stop;
                    owl:sameAs/lexinfo:partOfSpeech/rdfs:label ?pos .
  FILTER(!?stop)
}
ORDER BY DESC(?freq)
